@ResumeParserBackend_HostAddress = http://localhost:5226

GET {{ResumeParserBackend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{ResumeParserBackend_HostAddress}}/match/
Content-Type: application/json

{
    "must": ["a", "b"],
    "should": ["c"]
}

###

GET {{ResumeParserBackend_HostAddress}}/find/test